const ingredientsArray = [
  'lime',
  'brown sugar',
  'passion fruit juice',
  'ginger ale',
  'ice',
  'coffee',
  'sugar',
  'water',
  'milk',
  'scotch',
  'half-and-half',
  'condensed milk',
  'coconut syrup',
  'chocolate syrup',
  'vodka',
  'iced tea',
  'lemon juice',
  'irish whiskey',
  'peach brandy',
  'orange juice',
  'sweet and sour',
  'orange',
  'cherry',
  'whipped cream',
  'light rum',
  'blended whiskey',
  'lemon',
  'powdered sugar',
  'carbonated water',
  'kahlua',
  'coca-cola',
  'guinness stout',
  'lime juice',
  'gin',
  'aperol',
  'baileys irish cream',
  'bourbon',
  'grand marnier',
  'grenadine',
  'amaretto',
  'cognac',
  'heavy cream',
  'egg white',
  'dark rum',
  'absolut vodka',
  'tonic water',
  '151 proof rum',
  'wild turkey',
  'applejack',
  'grapefruit juice',
  'strawberry schnapps',
  'cranberry juice',
  'club soda',
  'apple juice',
  'maraschino cherry',
  'pisang ambon',
  'lemonade',
  'peach nectar',
  'vermouth',
  'triple sec',
  'mint',
  'sweet vermouth',
  'dry vermouth',
  'orange bitters',
  'maraschino liqueur',
  'creme de cacao',
  'light cream',
  'nutmeg',
  'pineapple juice',
  'blackberry brandy',
  'lemon peel',
  'bitters',
  'soda water',
  'frangelico',
  'cream',
  'creme de banane',
  'red wine',
  'peach schnapps',
  'pepsi cola',
  'prosecco',
  'campari',
  'ricard',
  'peychaud bitters',
  'brandy',
  'cointreau',
  'white creme de menthe',
  'advocaat',
  'jim beam',
  'jack daniels',
  'allspice',
  'rum',
  'champagne',
  'orange spiral',
  'salt',
  'apricot brandy',
  'cloves',
  'cinnamon',
  'sherry',
  'egg',
  'godiva liqueur',
  'anisette',
  'banana',
  'honey',
  'apple',
  'fresca',
  'malibu rum',
  'cherries',
  'curacao',
  'blue curacao',
  'sour mix',
  'lemon-lime soda',
  'absolut citron',
  'cocoa powder',
  'vanilla extract',
  'peach bitters',
  'lager',
  'cider',
  'blackcurrant cordial',
  'everclear',
  'fruit punch',
  'sprite',
  'tequila',
  'olive',
  'sambuca',
  'olive brine',
  'cherry heering',
  'demerara sugar',
  'cachaca',
  'pisco',
  'pineapple syrup',
  'st. germain',
  'angostura bitters',
  'pepper',
  'lavender',
  'ginger beer',
  'whiskey',
  'hot damn',
  'dubonnet rouge',
  'vanilla',
  'chocolate',
  'absinthe',
  'white rum',
  'galliano',
  'yoghurt',
  'fruit',
  'lime peel',
  'beer',
  'drambuie',
  'asafoetida',
  'ginger',
  'cayenne pepper',
  'tia maria',
  'mango',
  'corona',
  'bacardi limon',
  'coconut liqueur',
  'cumin seed',
  'lillet blanc',
  'cherry brandy',
  'tomato juice',
  'sugar syrup',
  'maple syrup',
  'limeade',
  'schweppes russchian',
  'creme de cassis',
  'grape juice',
  'rye whiskey',
  'vanilla ice-cream',
  'oreo cookie',
  'spiced rum',
  'bailey',
  'butterscotch schnapps',
  'jagermeister',
  'goldschlager',
  'orange peel',
  'espresso',
  'grape soda',
  'orange curacao',
  'port',
  'egg yolk',
  'blended scotch',
  'honey syrup',
  'ginger syrup',
  'islay single malt scotch',
  'coconut milk',
  'pineapple',
  'passoa',
  'passion fruit syrup',
  'cherry liqueur',
  'orgeat syrup',
  'fresh lime juice',
  'green creme de menthe',
  'pink lemonade',
  'rosemary syrup',
  'rosemary',
  'green chartreuse',
  'irish cream',
  'creme de mure',
  'hot chocolate',
  'wormwood',
  'sloe gin',
  'midori melon liqueur',
  'jägermeister',
  'banana liqueur',
  'southern comfort',
  'mountain dew',
  'surge',
  'worcestershire sauce',
  'tabasco sauce',
  'johnnie walker',
  'whipping cream',
  'vanilla syrup',
  'mezcal',
  'chocolate liqueur',
  'coffee liqueur',
  'roses sweetened lime juice',
  'benedictine',
  'strawberries',
  'apricot nectar',
  'pomegranate juice',
  'raspberry liqueur',
  'lillet',
  'fruit juice',
  'firewater',
  'absolut peppar',
  'dr. pepper',
  'sarsaparilla',
  '7-up',
  'grain alcohol',
  'absolut kurant',
  'tea',
  'kiwi liqueur',
  'bitter lemon',
  'cranberry vodka',
  'apfelkorn',
  'kool-aid',
  'kiwi',
  'papaya',
  'peach vodka',
  'falernum',
  'añejo rum',
  'blackstrap rum',
  'caramel coloring',
  'wine',
  'peppermint extract',
  'food coloring',
  'almond flavoring',
  'rumple minze',
  'whisky',
  'blackberries',
  'carbonated soft drink',
  'sherbet',
  'corn syrup',
  'cherry juice',
  'red chili flakes',
  'butter',
  'marshmallows',
  'cream of coconut',
  'white wine',
  'apple brandy',
  'vanilla vodka',
  'blueberry schnapps',
  'peachtree schnapps',
  'root beer',
  'gold rum',
  'pernod',
  'ouzo',
  'chambord raspberry liqueur',
  'zima',
  'crown royal',
  'raspberry syrup',
  'raspberry vodka',
  'coffee brandy',
  'lime vodka',
  'black sambuca',
  'pina colada mix',
  'daiquiri mix',
  'cardamom',
  'black pepper',
  'cucumber',
  'tropicana',
  'dark creme de cacao',
  'strawberry liqueur',
  'sirup of roses',
  'celery salt',
  'coriander',
  'anis',
  'elderflower cordial',
  'rosso vermouth',
  'melon liqueur',
  'yukon jack',
  'agave syrup',
  'jello',
  'mint syrup',
  'yellow chartreuse',
  'tennessee whiskey'
];

const ingredients = ingredientsArray.map(ingredient => {
  const obj = { 'name' : ingredient }
  return obj;
});

export default ingredients;